# Generated by Django 6.0.5 on 2026-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=32)),
                ('Branch', models.CharField(max_length=32)),
            ],
        ),
    ]
