# Generated by Django 6.0.5 on 2026-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=32)),
                ('emp_name', models.CharField(max_length=32)),
                ('designation', models.CharField(max_length=32)),
            ],
        ),
    ]
